const products=[
 {id:'celine',name:'Vestido Celine',price:1290,cat:'vestidos',color:'Preto',tag:'Novo',new:true,img:'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=1000&q=85',desc:'Vestido em crepe de alfaiataria com decote preciso e caimento fluido.'},
 {id:'alba',name:'Blazer Alba',price:1490,cat:'alfaiataria',color:'Areia',tag:'Exclusivo',new:true,img:'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=1000&q=85',desc:'Blazer de corte reto em lã fria, acabamento interno impecável.'},
 {id:'lina',name:'Calça Lina',price:890,cat:'alfaiataria',color:'Chocolate',img:'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=1000&q=85',desc:'Calça de cintura alta e pernas amplas em crepe com toque de seda.'},
 {id:'elis',name:'Camisa Elis',price:690,cat:'camisas',color:'Off white',tag:'Novo',new:true,img:'https://images.unsplash.com/photo-1605763240000-7e93b172d754?auto=format&fit=crop&w=1000&q=85',desc:'Camisa de seda pura com colarinho minimalista.'},
 {id:'iris',name:'Tricot Íris',price:790,cat:'tricots',color:'Caramelo',img:'https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?auto=format&fit=crop&w=1000&q=85',desc:'Tricot leve com textura sofisticada para acompanhar a estação.'},
 {id:'maya',name:'Saia Maya',price:740,cat:'saias',color:'Preto',img:'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1000&q=85',desc:'Saia midi de caimento fluido e acabamento minimalista.'},
 {id:'ambre',name:'Casaco Ambre',price:1890,cat:'casacos',color:'Areia',tag:'Últimas peças',img:'https://images.unsplash.com/photo-1548126032-079a0fb0099d?auto=format&fit=crop&w=1000&q=85',desc:'Casaco de lã com corte generoso e construção impecável.'},
 {id:'aurora',name:'Conjunto Aurora',price:1780,cat:'alfaiataria',color:'Preto',img:'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=1000&q=85',desc:'Conjunto de alfaiataria que combina rigor e movimento.'}
];
let cart=JSON.parse(localStorage.getItem('rf-cart')||'[]'), favorites=JSON.parse(localStorage.getItem('rf-favorites')||'[]'), profile=JSON.parse(localStorage.getItem('rf-profile')||'null'), activeFilter='all';
const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const byId=id=>products.find(p=>p.id===id); const save=()=>{localStorage.setItem('rf-cart',JSON.stringify(cart));localStorage.setItem('rf-favorites',JSON.stringify(favorites));updateBadges()};
function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function card(p){return `<article class="card"><button class="heart" data-fav="${p.id}" aria-label="Favoritar ${p.name}">${favorites.includes(p.id)?'♥':'♡'}</button><a class="card-image" href="#produto" data-product="${p.id}">${p.tag?`<span class="tag">${p.tag}</span>`:''}<img src="${p.img}" alt="${p.name}"></a><a href="#produto" data-product="${p.id}" class="meta"><p>${p.name}<br><span class="muted">${p.color}</span></p><span class="price">${money(p.price)}</span></a></article>`}
function renderProducts(){const filtered=activeFilter==='all'?products:activeFilter==='new'?products.filter(p=>p.new):products.filter(p=>p.cat===activeFilter);document.querySelector('#product-grid').innerHTML=filtered.map(card).join('');document.querySelector('#product-total').textContent=`${filtered.length} peças`;document.querySelector('#shop-title').textContent=activeFilter==='all'?'Todos os produtos':activeFilter==='new'?'Novidades':activeFilter[0].toUpperCase()+activeFilter.slice(1)}
function updateBadges(){document.querySelector('#cart-count').textContent=cart.reduce((n,x)=>n+x.qty,0)||'';document.querySelector('#favorite-count').textContent=favorites.length||''}
function open(id){document.querySelector('#'+id).classList.add('open');document.querySelector('#'+id).setAttribute('aria-hidden','false')}function closeAll(){document.querySelectorAll('.modal').forEach(x=>{x.classList.remove('open');x.setAttribute('aria-hidden','true')})}
function detail(id){const p=byId(id);document.querySelector('#product-detail').innerHTML=`<img src="${p.img}" alt="${p.name}"><div><button class="detail-heart" data-fav="${p.id}" aria-label="Favoritar">${favorites.includes(p.id)?'♥':'♡'}</button><span class="eyebrow">${p.cat}</span><h2>${p.name}</h2><p class="price">${money(p.price)}</p><p class="muted">ou 6x de ${money(p.price/6)} sem juros</p><hr><p>${p.desc}</p><p class="eyebrow">Selecione o tamanho</p><div class="size-row">${['PP','P','M','G','GG'].map(x=>`<button data-size="${x}">${x}</button>`).join('')}</div><button class="guide">Guia de medidas</button><div class="guide-info">PP: 34–36 · P: 38 · M: 40 · G: 42 · GG: 44–46<br>As medidas são aproximadas e tomadas sobre o corpo.</div><button class="button dark add-cart" data-add="${p.id}">Adicionar à sacola →</button><p class="muted">Frete gratuito acima de R$ 1.200</p></div>`;open('product-modal')}
function addCart(id){const size=document.querySelector('[data-size].active')?.dataset.size;if(!size){toast('Selecione um tamanho antes de adicionar.');return}const old=cart.find(x=>x.id===id&&x.size===size);old?old.qty++:cart.push({id,size,qty:1});save();toast('Peça adicionada à sua sacola.');}
function renderCart(){const box=document.querySelector('#cart-items'), total=cart.reduce((s,x)=>s+byId(x.id).price*x.qty,0);box.innerHTML=cart.length?cart.map(x=>{const p=byId(x.id);return `<div class="cart-line"><img src="${p.img}" alt=""><div>${p.name}<br><span class="muted">${p.color} · ${x.size} · qtd. ${x.qty}</span><br><button class="remove" data-remove="${x.id}|${x.size}">Remover</button></div><span class="price">${money(p.price*x.qty)}</span></div>`}).join(''):'<p class="muted">Sua sacola está vazia.</p>';document.querySelector('#cart-summary').innerHTML=cart.length?`<div class="summary"><p><span>Subtotal</span><span>${money(total)}</span></p><p><span>Entrega</span><span>A calcular</span></p><hr><p><b>Total</b><b>${money(total)}</b></p><button class="button dark" id="checkout">Finalizar compra</button></div>`:''}
function renderFavorites(){document.querySelector('#favorite-items').innerHTML=favorites.length?favorites.map(id=>{const p=byId(id);return `<div class="favorite-line"><img src="${p.img}" alt=""><div>${p.name}<br><span class="price">${money(p.price)}</span><br><button class="remove" data-product="${p.id}">Ver produto</button></div><button class="remove" data-fav="${p.id}">Remover</button></div>`}).join(''):'<p class="muted">Ainda não há peças favoritada.</p>'}
function renderAccount(tab='orders'){const auth=document.querySelector('#auth-area'),area=document.querySelector('#account-area');if(!profile){area.hidden=true;auth.innerHTML=`<p>Entre ou crie seu perfil para acompanhar suas escolhas.</p><form class="auth-form" id="login-form"><input name="name" placeholder="Nome completo" required><input name="email" type="email" placeholder="E-mail" required><input name="password" type="password" placeholder="Senha" required><button class="button dark">Criar conta / entrar</button></form>`;return}auth.innerHTML=`<p>Olá, <b>${profile.name}</b>.</p>`;area.hidden=false;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const content=document.querySelector('#account-content');const pages={orders:'<h3>Meus pedidos</h3><p>Você ainda não fez pedidos. Assim que fizer uma compra, o acompanhamento aparecerá aqui.</p>',profile:`<h3>Dados pessoais</h3><p><b>${profile.name}</b><br>${profile.email}</p><button class="text-link" id="edit-profile">Editar dados</button>`,addresses:'<h3>Endereços</h3><p>Nenhum endereço cadastrado.</p><button class="button dark" id="add-address">Adicionar endereço</button>',favorites:`<h3>Favoritos</h3><p>${favorites.length?`${favorites.length} peça(s) salva(s).`: 'Você ainda não salvou peças.'}</p><button class="text-link" id="open-favs">Ver favoritos</button>`};content.innerHTML=pages[tab]}
document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;if(el.dataset.close!==undefined||e.target.classList.contains('modal')){closeAll();return}if(el.dataset.filter){activeFilter=el.dataset.filter;renderProducts();document.querySelector('#loja').scrollIntoView({behavior:'smooth'});return}if(el.dataset.product){e.preventDefault();detail(el.dataset.product);return}if(el.dataset.fav){const id=el.dataset.fav;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];save();renderProducts();renderFavorites();if(document.querySelector('#product-modal').classList.contains('open'))detail(id);toast(favorites.includes(id)?'Peça salva nos favoritos.':'Peça removida dos favoritos.');return}if(el.dataset.size){document.querySelectorAll('[data-size]').forEach(x=>x.classList.remove('active'));el.classList.add('active');return}if(el.classList.contains('guide')){document.querySelector('.guide-info').classList.toggle('show');return}if(el.dataset.add){addCart(el.dataset.add);return}if(el.dataset.remove){const [id,size]=el.dataset.remove.split('|');cart=cart.filter(x=>x.id!==id||x.size!==size);save();renderCart();return}if(el.id==='search-btn'){open('search-modal');setTimeout(()=>document.querySelector('#search-input').focus(),100)}if(el.id==='cart-btn'){renderCart();open('cart-modal')}if(el.id==='favorites-btn'){renderFavorites();open('favorites-modal')}if(el.id==='account-btn'){renderAccount();open('account-modal')}if(el.id==='stores-btn'){open('stores-modal')}if(el.id==='logout-btn'){profile=null;localStorage.removeItem('rf-profile');renderAccount();toast('Você saiu da sua conta.')}if(el.dataset.tab){renderAccount(el.dataset.tab)}if(el.id==='open-favs'){renderFavorites();open('favorites-modal')}if(el.id==='checkout'){toast('Checkout demonstrativo: integração de pagamento será conectada aqui.')}if(el.id==='add-address'){toast('Cadastro de endereço aberto no checkout.')}if(el.classList.contains('menu-toggle'))document.querySelector('nav').classList.toggle('open')});
document.querySelector('#newsletter-form').addEventListener('submit',e=>{e.preventDefault();const email=document.querySelector('#newsletter-email');localStorage.setItem('rf-newsletter',email.value);email.value='';toast('Obrigada! Você agora recebe a Carta Renata Felix.');});document.querySelector('#search-input').addEventListener('input',e=>{const results=products.filter(p=>`${p.name} ${p.cat} ${p.color}`.toLowerCase().includes(e.target.value.toLowerCase()));document.querySelector('#search-results').innerHTML=results.map(p=>`<a data-product="${p.id}" class="search-result"><img src="${p.img}" alt="${p.name}"><p>${p.name}<br><span class="price">${money(p.price)}</span></p></a>`).join('')||'<p>Nenhuma peça encontrada.</p>'});document.addEventListener('submit',e=>{if(e.target.id==='login-form'){e.preventDefault();profile={name:e.target.elements.name.value,email:e.target.elements.email.value};localStorage.setItem('rf-profile',JSON.stringify(profile));renderAccount();toast('Perfil criado com sucesso.')}});
document.querySelector('#new-grid').innerHTML=products.filter(p=>p.new).map(card).join('');renderProducts();updateBadges();
